# Generated by Django 6.0 on 2025-12-14 09:01

import django.db.models.deletion
from django.conf import settings
from django.contrib.auth import get_user_model
from django.db import migrations, models


def migrate_news_authors_to_users(apps, schema_editor):
    """Create User objects for existing author strings and map them"""
    News = apps.get_model('news', 'News')
    User = get_user_model()
    db_table = News._meta.db_table
    
    # Get all unique author names from the database directly
    with schema_editor.connection.cursor() as cursor:
        cursor.execute(f"SELECT DISTINCT author FROM {db_table} WHERE author IS NOT NULL AND author != ''")
        unique_authors = [row[0] for row in cursor.fetchall()]
    
    # Create a mapping of author name to User ID
    author_to_user_id = {}
    
    for author_name in unique_authors:
        if author_name:  # Skip empty strings
            # Create username from author name
            username = author_name.lower().replace(' ', '_').replace("'", '').replace('.', '')[:150]
            # Ensure username is unique
            base_username = username
            counter = 1
            while User.objects.filter(username=username).exists():
                username = f"{base_username}_{counter}"[:150]
                counter += 1
            
            # Create user
            user, created = User.objects.get_or_create(
                username=username,
                defaults={
                    'first_name': author_name.split()[0] if author_name.split() else author_name[:30],
                    'last_name': ' '.join(author_name.split()[1:])[:30] if len(author_name.split()) > 1 else '',
                    'email': f'{username}@parliamentwatch.ug',
                }
            )
            author_to_user_id[author_name] = user.id
    
    # Update all News objects using raw SQL
    with schema_editor.connection.cursor() as cursor:
        for author_name, user_id in author_to_user_id.items():
            cursor.execute(
                f"UPDATE {db_table} SET author_temp_id = %s WHERE author = %s",
                [user_id, author_name]
            )


def reverse_migrate_news_authors(apps, schema_editor):
    """Reverse migration - not implemented"""
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0004_alter_news_content'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='news',
            name='excerpt',
        ),
        # Add temporary integer field to store user IDs
        migrations.AddField(
            model_name='news',
            name='author_temp_id',
            field=models.IntegerField(null=True, blank=True),
        ),
        # Run data migration to create users and populate author_temp_id
        migrations.RunPython(migrate_news_authors_to_users, reverse_migrate_news_authors),
        # Remove old author CharField
        migrations.RemoveField(
            model_name='news',
            name='author',
        ),
        # Rename author_temp_id to author
        migrations.RenameField(
            model_name='news',
            old_name='author_temp_id',
            new_name='author',
        ),
        # Convert to ForeignKey
        migrations.AlterField(
            model_name='news',
            name='author',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='news_articles', to=settings.AUTH_USER_MODEL),
        ),
    ]
