# Generated by Django 6.0 on 2026-01-09 07:33

import ckeditor.fields
import django.db.models.deletion
import news.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0005_remove_news_excerpt_alter_news_author'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HotInParliament',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(db_index=True, max_length=500)),
                ('slug', models.SlugField(blank=True, max_length=550, unique=True)),
                ('content', ckeditor.fields.RichTextField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='hot_in_parliament/')),
                ('link_url', models.URLField(blank=True, help_text='Optional link to related article or external resource', null=True)),
                ('is_active', models.BooleanField(default=True, help_text='Whether this item should be displayed')),
                ('order', models.PositiveIntegerField(default=0, help_text='Order for display (lower numbers appear first)')),
                ('published_date', models.DateField(default=news.models.default_published_date)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='hot_in_parliament', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Hot in Parliament',
                'verbose_name_plural': 'Hot in Parliament',
                'ordering': ['order', '-published_date', '-created_at'],
            },
        ),
    ]
