# Generated by Django 6.0

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0007_newscomment'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='view_count',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
