# Generated by Django

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0008_add_view_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='hotinparliament',
            name='view_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.CreateModel(
            name='HotInParliamentComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author_name', models.CharField(max_length=255)),
                ('author_email', models.EmailField(max_length=254)),
                ('body', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_approved', models.BooleanField(default=True, help_text='Approved comments are shown publicly')),
                ('hot_item', models.ForeignKey(db_index=True, on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='news.hotinparliament')),
            ],
            options={
                'verbose_name': 'Hot in Parliament comment',
                'verbose_name_plural': 'Hot in Parliament comments',
                'ordering': ['-created_at'],
            },
        ),
    ]
