# Generated by Django 6.0 on 2026-02-11 06:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0009_hotinparliament_view_count_hotinparliamentcomment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='category',
            field=models.CharField(choices=[('news_updates', 'News and Updates'), ('parliament', 'Parliament News'), ('governance', 'Governance'), ('accountability', 'Accountability')], default='news_updates', max_length=50),
        ),
    ]
