# Generated by Django 6.0 on 2025-12-11 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='XSpace',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Title of the X Space event', max_length=200)),
                ('description', models.TextField(blank=True, help_text='Description of the event')),
                ('host', models.CharField(help_text='Host or organizer of the X Space', max_length=200)),
                ('scheduled_date', models.DateTimeField(help_text='Scheduled date and time for the X Space')),
                ('duration', models.IntegerField(blank=True, help_text='Duration in minutes', null=True)),
                ('x_space_url', models.URLField(help_text='URL to the X Space event')),
                ('recording_url', models.URLField(blank=True, help_text='URL to recording if available', null=True)),
                ('thumbnail', models.ImageField(blank=True, help_text='Thumbnail image for the event', null=True, upload_to='x_spaces/')),
                ('status', models.CharField(choices=[('upcoming', 'Upcoming'), ('live', 'Live'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='upcoming', help_text='Current status of the X Space', max_length=20)),
                ('topics', models.CharField(blank=True, help_text='Comma-separated list of topics to be discussed', max_length=500)),
                ('speakers', models.TextField(blank=True, help_text='List of speakers/participants (one per line or comma-separated)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'X Space',
                'verbose_name_plural': 'X Spaces',
                'ordering': ['-scheduled_date', '-created_at'],
            },
        ),
    ]
