# Generated by Django 6.0 on 2025-12-11 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('multimedia', '0003_remove_podcast_likes_remove_podcast_views_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Gallery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Title of the gallery image', max_length=200)),
                ('description', models.TextField(blank=True, help_text='Description of the image')),
                ('image', models.ImageField(help_text='Gallery image', upload_to='gallery/')),
                ('category', models.CharField(blank=True, help_text='Category of the image (e.g., Events, Parliament, Activities)', max_length=100)),
                ('event_date', models.DateField(blank=True, help_text='Date when the event/photograph was taken', null=True)),
                ('photographer', models.CharField(blank=True, help_text='Photographer or source', max_length=200)),
                ('tags', models.CharField(blank=True, help_text='Comma-separated list of tags', max_length=500)),
                ('featured', models.BooleanField(default=False, help_text='Whether this image should be featured')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Gallery Image',
                'verbose_name_plural': 'Gallery Images',
                'ordering': ['-featured', '-event_date', '-created_at'],
            },
        ),
    ]
