# Generated by Django 6.0 on 2025-12-11 19:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('multimedia', '0004_gallery'),
    ]

    operations = [
        migrations.CreateModel(
            name='Poll',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Poll question or title', max_length=300)),
                ('description', models.TextField(blank=True, help_text='Detailed description of the poll')),
                ('category', models.CharField(blank=True, help_text='Category or topic (e.g., Legislation, Budget, Governance)', max_length=100)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('active', 'Active'), ('closed', 'Closed')], default='draft', help_text='Current status of the poll', max_length=20)),
                ('start_date', models.DateTimeField(blank=True, help_text='When the poll becomes active', null=True)),
                ('end_date', models.DateTimeField(blank=True, help_text='When the poll closes', null=True)),
                ('allow_multiple_votes', models.BooleanField(default=False, help_text='Allow users to vote multiple times')),
                ('show_results_before_voting', models.BooleanField(default=False, help_text='Show results before user votes')),
                ('featured', models.BooleanField(default=False, help_text='Feature this poll on the homepage')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Poll',
                'verbose_name_plural': 'Polls',
                'ordering': ['-featured', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PollOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(help_text='Option text', max_length=500)),
                ('order', models.IntegerField(default=0, help_text='Display order')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('poll', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='options', to='multimedia.poll')),
            ],
            options={
                'verbose_name': 'Poll Option',
                'verbose_name_plural': 'Poll Options',
                'ordering': ['order', 'created_at'],
            },
        ),
        migrations.CreateModel(
            name='PollVote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_address', models.GenericIPAddressField(blank=True, help_text="Voter's IP address", null=True)),
                ('session_id', models.CharField(blank=True, help_text='Session identifier', max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('option', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='votes', to='multimedia.polloption')),
                ('poll', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='votes', to='multimedia.poll')),
            ],
            options={
                'verbose_name': 'Poll Vote',
                'verbose_name_plural': 'Poll Votes',
                'ordering': ['-created_at'],
            },
        ),
    ]
