# Generated by Django 6.0 on 2025-12-13 05:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('multimedia', '0005_poll_polloption_pollvote'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gallery',
            name='title',
            field=models.CharField(db_index=True, help_text='Title of the gallery image', max_length=200),
        ),
        migrations.AlterField(
            model_name='podcast',
            name='host',
            field=models.CharField(db_index=True, help_text='Host or presenter of the podcast', max_length=200),
        ),
        migrations.AlterField(
            model_name='podcast',
            name='title',
            field=models.CharField(db_index=True, help_text='Title of the podcast episode', max_length=200),
        ),
        migrations.AlterField(
            model_name='poll',
            name='title',
            field=models.CharField(db_index=True, help_text='Poll question or title', max_length=300),
        ),
        migrations.AlterField(
            model_name='xspace',
            name='host',
            field=models.CharField(db_index=True, help_text='Host or organizer of the X Space', max_length=200),
        ),
        migrations.AlterField(
            model_name='xspace',
            name='title',
            field=models.CharField(db_index=True, help_text='Title of the X Space event', max_length=200),
        ),
    ]
