# Generated by Django

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('multimedia', '0006_alter_gallery_title_alter_podcast_host_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='XPoll',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('x_poll_url', models.URLField(help_text='URL to the X (Twitter) post where this poll was created. Users can view or vote on X too.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('poll', models.OneToOneField(help_text='The poll on this site that mirrors the X poll', on_delete=django.db.models.deletion.CASCADE, related_name='x_poll_link', to='multimedia.poll')),
            ],
            options={
                'verbose_name': 'X Poll',
                'verbose_name_plural': 'X Polls',
                'ordering': ['-created_at'],
            },
        ),
    ]
