# Generated by Django

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('multimedia', '0007_xpoll'),
    ]

    operations = [
        migrations.AddField(
            model_name='xpoll',
            name='embed_html',
            field=models.TextField(
                blank=True,
                help_text="Paste the full blockquote HTML from Twitter's 'Embed Tweet' (the <blockquote class=\"twitter-tweet\">...</blockquote> part). Required for the poll and vote options to show."
            ),
        ),
    ]
