# Generated by Django

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('multimedia', '0008_xpoll_embed_html'),
    ]

    operations = [
        migrations.CreateModel(
            name='XPollEmbed',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, help_text='Optional label for admin (e.g. poll topic)', max_length=200)),
                ('embed_html', models.TextField(help_text='Paste the full embed from Twitter: the <blockquote class="twitter-tweet">...</blockquote> part (script is loaded on the page).')),
                ('order', models.PositiveIntegerField(default=0, help_text='Display order (lower first)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'X Poll Embed',
                'verbose_name_plural': 'X Poll Embeds',
                'ordering': ['order', '-created_at'],
            },
        ),
    ]
