# Generated by Django

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('multimedia', '0009_xpollembed'),
    ]

    operations = [
        migrations.DeleteModel(name='XPoll'),
    ]
