# Generated by Django 6.0

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('multimedia', '0010_delete_xpoll'),
    ]

    operations = [
        migrations.CreateModel(
            name='Trivia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(db_index=True, help_text='Title of the trivia set', max_length=200)),
                ('description', models.TextField(blank=True, help_text='Short description shown on the card')),
                ('image', models.ImageField(blank=True, help_text='Optional cover image for the trivia card', null=True, upload_to='trivia/')),
                ('order', models.PositiveIntegerField(default=0, help_text='Display order (lower first)')),
                ('is_active', models.BooleanField(default=True, help_text='Show on Citizens Voice page')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Trivia',
                'verbose_name_plural': 'Trivia',
                'ordering': ['order', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TriviaQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_text', models.TextField(help_text='The question shown on the card')),
                ('answer_text', models.TextField(blank=True, help_text='Optional answer to reveal (e.g. for quiz-style trivia)')),
                ('order', models.PositiveIntegerField(default=0, help_text='Order within the trivia')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('trivia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='multimedia.trivia')),
            ],
            options={
                'verbose_name': 'Trivia Question',
                'verbose_name_plural': 'Trivia Questions',
                'ordering': ['order', 'created_at'],
            },
        ),
    ]
