# Generated by Django 6.0

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('multimedia', '0011_trivia_triviaquestion'),
    ]

    operations = [
        migrations.CreateModel(
            name='TriviaOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(help_text='Option text', max_length=500)),
                ('is_correct', models.BooleanField(default=False, help_text='Whether this is the correct answer')),
                ('order', models.PositiveIntegerField(default=0, help_text='Display order')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='options', to='multimedia.triviaquestion')),
            ],
            options={
                'verbose_name': 'Trivia Option',
                'verbose_name_plural': 'Trivia Options',
                'ordering': ['order', 'created_at'],
            },
        ),
    ]
