# Generated by Django 6.0 on 2026-02-11 06:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('multimedia', '0012_triviaoption'),
    ]

    operations = [
        migrations.AlterField(
            model_name='triviaquestion',
            name='answer_text',
            field=models.TextField(blank=True, help_text='Optional answer to reveal (used if no options provided, or as explanation)'),
        ),
    ]
