# Generated by Django 6.0 on 2025-12-10 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trackers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MP',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('middle_name', models.CharField(blank=True, max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('name', models.CharField(help_text='Full name of the MP', max_length=300)),
                ('phone_no', models.CharField(blank=True, max_length=20)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('party', models.CharField(choices=[('nrm', 'National Resistance Movement (NRM)'), ('nup', 'National Unity Platform (NUP)'), ('fdc', 'Forum for Democratic Change (FDC)'), ('dp', 'Democratic Party (DP)'), ('independent', 'Independent'), ('other', 'Other')], max_length=100)),
                ('constituency', models.CharField(max_length=200)),
                ('district', models.CharField(max_length=100)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='mps/')),
                ('bio', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Member of Parliament',
                'verbose_name_plural': 'Members of Parliament',
                'ordering': ['last_name', 'first_name'],
            },
        ),
    ]
