# Generated by Django 6.0 on 2025-12-10 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trackers', '0002_mp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mp',
            name='party',
            field=models.CharField(help_text='Political party affiliation', max_length=100),
        ),
    ]
