# Generated by Django 6.0 on 2025-12-11 20:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trackers', '0007_budget_orderpaper_alter_hansard_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='Committee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Committee name', max_length=300)),
                ('description', models.TextField(blank=True, help_text='Committee description and mandate')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('chairperson', models.ForeignKey(blank=True, help_text='Committee chairperson', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='committees_chaired', to='trackers.mp')),
                ('deputy_chairperson', models.ForeignKey(blank=True, help_text='Committee deputy chairperson', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='committees_deputy_chaired', to='trackers.mp')),
                ('members', models.ManyToManyField(blank=True, help_text='Committee members', related_name='committee_memberships', to='trackers.mp')),
            ],
            options={
                'verbose_name': 'Committee',
                'verbose_name_plural': 'Committees',
                'ordering': ['title'],
            },
        ),
        migrations.CreateModel(
            name='CommitteeDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Document title', max_length=300)),
                ('description', models.TextField(blank=True, help_text='Document description')),
                ('file', models.FileField(help_text='Document file', upload_to='committee_documents/')),
                ('document_date', models.DateField(blank=True, help_text='Document date', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('committee', models.ForeignKey(help_text='Associated committee', on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='trackers.committee')),
            ],
            options={
                'verbose_name': 'Committee Document',
                'verbose_name_plural': 'Committee Documents',
                'ordering': ['-document_date', '-created_at'],
            },
        ),
    ]
