# Generated by Django 6.0 on 2025-12-13 05:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trackers', '0008_committee_committeedocument'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bill',
            name='mover',
            field=models.CharField(db_index=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='bill',
            name='title',
            field=models.CharField(db_index=True, max_length=500),
        ),
        migrations.AlterField(
            model_name='billreading',
            name='stage',
            field=models.CharField(choices=[('1st_reading', '1st Reading'), ('2nd_reading', '2nd Reading'), ('3rd_reading', '3rd Reading'), ('waiting_assent', 'Waiting for Assent'), ('assented', 'Assented to by the President'), ('withdrawn', 'Withdrawn')], max_length=50),
        ),
        migrations.AlterField(
            model_name='budget',
            name='name',
            field=models.CharField(db_index=True, help_text='Budget document name', max_length=200),
        ),
        migrations.AlterField(
            model_name='hansard',
            name='name',
            field=models.CharField(db_index=True, help_text='Hansard name', max_length=50),
        ),
        migrations.AlterField(
            model_name='loan',
            name='label',
            field=models.CharField(db_index=True, help_text='Project name or description', max_length=500),
        ),
        migrations.AlterField(
            model_name='loan',
            name='source',
            field=models.CharField(choices=[('world_bank', 'World Bank'), ('imf', 'International Monetary Fund'), ('adb', 'African Development Bank'), ('china', 'China'), ('eu', 'European Union'), ('bilateral', 'Bilateral Agreement'), ('other', 'Other')], db_index=True, help_text='Loan source/creditor', max_length=50),
        ),
        migrations.AlterField(
            model_name='mp',
            name='constituency',
            field=models.CharField(db_index=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='mp',
            name='district',
            field=models.CharField(db_index=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='mp',
            name='name',
            field=models.CharField(db_index=True, help_text='Full name of the MP', max_length=300),
        ),
        migrations.AlterField(
            model_name='mp',
            name='party',
            field=models.CharField(db_index=True, help_text='Political party affiliation', max_length=100),
        ),
        migrations.AlterField(
            model_name='orderpaper',
            name='name',
            field=models.CharField(db_index=True, max_length=100),
        ),
    ]
