# Generated by Django 6.0 on 2025-12-13 14:26

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trackers', '0009_alter_bill_mover_alter_bill_title_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bill',
            name='comments',
        ),
        migrations.RemoveField(
            model_name='bill',
            name='likes',
        ),
        migrations.RemoveField(
            model_name='bill',
            name='shares',
        ),
        migrations.AlterField(
            model_name='mp',
            name='bio',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
    ]
