# Generated by Django

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trackers', '0012_committee_begin_date_end_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='Lender',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Lender',
                'verbose_name_plural': 'Lenders',
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='loan',
            name='lender',
            field=models.ForeignKey(
                blank=True,
                help_text='Lender/provider. Add new in Lenders if not listed.',
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name='loans',
                to='trackers.lender',
            ),
        ),
        migrations.AlterField(
            model_name='loan',
            name='source',
            field=models.CharField(
                blank=True,
                choices=[
                    ('world_bank', 'World Bank'),
                    ('imf', 'International Monetary Fund'),
                    ('adb', 'African Development Bank'),
                    ('china', 'China'),
                    ('eu', 'European Union'),
                    ('bilateral', 'Bilateral Agreement'),
                    ('other', 'Other'),
                ],
                db_index=True,
                help_text='Fallback if lender not set (legacy)',
                max_length=50,
            ),
        ),
        migrations.CreateModel(
            name='LoanDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(help_text='e.g. Proposal, Report, Agreement', max_length=200)),
                ('file', models.FileField(upload_to='loans/documents/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('loan', models.ForeignKey(db_index=True, on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='trackers.loan')),
            ],
            options={
                'verbose_name': 'Loan document',
                'verbose_name_plural': 'Loan documents',
                'ordering': ['label'],
            },
        ),
    ]
