# Generated by Django

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trackers', '0013_lender_loandocument_loan_lender'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loan',
            name='description',
            field=ckeditor.fields.RichTextField(blank=True),
        ),
    ]
