# Generated by Django

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('trackers', '0014_alter_loan_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='ParliamentTerm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='e.g. 11th Parliament', max_length=100)),
                ('start_year', models.IntegerField(help_text='e.g. 2021')),
                ('end_year', models.IntegerField(help_text='e.g. 2026')),
                ('is_current', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Parliament Term',
                'verbose_name_plural': 'Parliament Terms',
                'ordering': ['-start_year'],
            },
        ),
        migrations.AddField(
            model_name='mp',
            name='parliament_term',
            field=models.ForeignKey(
                blank=True,
                help_text='Parliament term this MP belongs to',
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name='mps',
                to='trackers.parliamentterm',
            ),
        ),
    ]
