# Generated by Django - backfill existing MPs to current term

from django.db import migrations


def create_current_term_and_assign_mps(apps, schema_editor):
    ParliamentTerm = apps.get_model('trackers', 'ParliamentTerm')
    MP = apps.get_model('trackers', 'MP')
    # Create one current term for existing data (11th Parliament 2021-2026)
    term, _ = ParliamentTerm.objects.get_or_create(
        start_year=2021,
        defaults={'name': '11th Parliament', 'end_year': 2026, 'is_current': True},
    )
    ParliamentTerm.objects.exclude(pk=term.pk).update(is_current=False)
    term.is_current = True
    term.save()
    # Assign all MPs that have no term to this term
    MP.objects.filter(parliament_term__isnull=True).update(parliament_term=term)


def noop_reverse(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('trackers', '0015_parliamentterm_mp_parliament_term'),
    ]

    operations = [
        migrations.RunPython(create_current_term_and_assign_mps, noop_reverse),
    ]
