# Generated by Django - committee chairperson/deputy as plain text

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trackers', '0016_backfill_parliament_term'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='committee',
            name='chairperson',
        ),
        migrations.RemoveField(
            model_name='committee',
            name='deputy_chairperson',
        ),
        migrations.AddField(
            model_name='committee',
            name='chairperson',
            field=models.CharField(blank=True, help_text='Committee chairperson', max_length=200),
        ),
        migrations.AddField(
            model_name='committee',
            name='deputy_chairperson',
            field=models.CharField(blank=True, help_text='Committee deputy chairperson', max_length=200),
        ),
    ]
