# Generated by Django 6.0 on 2025-12-12 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DonationSubmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=254)),
                ('country', models.CharField(default='United States', max_length=100)),
                ('address', models.TextField(blank=True)),
                ('donation_method', models.CharField(blank=True, choices=[('mobile-money', 'Mobile Money'), ('bank-transfer', 'Bank Transfer'), ('other', 'Other')], help_text='Preferred donation method', max_length=50)),
                ('message', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('new', 'New'), ('acknowledged', 'Acknowledged'), ('processed', 'Processed'), ('completed', 'Completed')], default='new', max_length=20)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Donation Submission',
                'verbose_name_plural': 'Donation Submissions',
                'ordering': ['-created_at'],
            },
        ),
    ]
