# Generated by Django 6.0

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CitizensVoiceFeedbackLinks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ask_mp_form_url', models.URLField(blank=True, help_text="Google form URL for 'Ask your MP'", max_length=500)),
                ('comment_bill_form_url', models.URLField(blank=True, help_text="Google form URL for 'Comment on a bill'", max_length=500)),
                ('feedback_law_form_url', models.URLField(blank=True, help_text="Google form URL for 'Feedback on a law'", max_length=500)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Citizens Voice feedback links',
                'verbose_name_plural': 'Citizens Voice feedback links',
            },
        ),
    ]
