# Generated by Django 6.0 on 2026-02-17 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0002_citizens_voice_feedback_links'),
    ]

    operations = [
        migrations.CreateModel(
            name='FooterDocuments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('terms_of_service', models.FileField(blank=True, help_text='Terms of Service document (PDF or other document format)', null=True, upload_to='footer_documents/')),
                ('privacy_policy', models.FileField(blank=True, help_text='Privacy Policy document (PDF or other document format)', null=True, upload_to='footer_documents/')),
                ('accessibility', models.FileField(blank=True, help_text='Accessibility statement document (PDF or other document format)', null=True, upload_to='footer_documents/')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Footer Documents',
                'verbose_name_plural': 'Footer Documents',
            },
        ),
    ]
