# Generated by Django 6.0 on 2025-12-11 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HeroImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, help_text='Optional title for the image', max_length=200)),
                ('image', models.ImageField(help_text='Hero image for the carousel', upload_to='hero/')),
                ('order', models.IntegerField(default=0, help_text='Display order (lower numbers appear first)')),
                ('is_active', models.BooleanField(default=True, help_text='Whether this image is active in the carousel')),
                ('alt_text', models.CharField(blank=True, help_text='Alternative text for accessibility', max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Hero Image',
                'verbose_name_plural': 'Hero Images',
                'ordering': ['order', 'created_at'],
            },
        ),
    ]
