# Generated by Django 6.0 on 2025-12-11 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Objective',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Objective title or number', max_length=200)),
                ('description', models.TextField(help_text='Detailed description of the objective')),
                ('order', models.IntegerField(default=0, help_text='Display order')),
                ('icon', models.CharField(blank=True, help_text='Icon name or identifier (optional)', max_length=100)),
                ('is_active', models.BooleanField(default=True, help_text='Whether this objective is active')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Objective',
                'verbose_name_plural': 'Objectives',
                'ordering': ['order', 'created_at'],
            },
        ),
        migrations.CreateModel(
            name='TeamMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Full name of the team member', max_length=200)),
                ('title', models.CharField(help_text='Job title or position', max_length=200)),
                ('bio', models.TextField(blank=True, help_text='Short biography')),
                ('photo', models.ImageField(blank=True, help_text='Team member photo', null=True, upload_to='team/')),
                ('email', models.EmailField(blank=True, help_text='Email address', max_length=254)),
                ('phone', models.CharField(blank=True, help_text='Phone number', max_length=20)),
                ('linkedin_url', models.URLField(blank=True, help_text='LinkedIn profile URL')),
                ('twitter_url', models.URLField(blank=True, help_text='Twitter profile URL')),
                ('facebook_url', models.URLField(blank=True, help_text='Facebook profile URL')),
                ('order', models.IntegerField(default=0, help_text='Display order')),
                ('is_active', models.BooleanField(default=True, help_text='Whether this team member is active')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Team Member',
                'verbose_name_plural': 'Team Members',
                'ordering': ['order', 'name'],
            },
        ),
    ]
