# Generated by Django 6.0 on 2026-01-09 09:39

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='OurStory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='Our Story', max_length=200)),
                ('content', ckeditor.fields.RichTextField(help_text='Content for the Our Story section')),
                ('image', models.ImageField(blank=True, help_text='Optional image for the section', null=True, upload_to='about/')),
                ('is_active', models.BooleanField(default=True, help_text='Whether this section is active')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Our Story',
                'verbose_name_plural': 'Our Story',
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='Partner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Partner organization name', max_length=200)),
                ('description', models.TextField(blank=True, help_text='Description of the partner')),
                ('logo', models.ImageField(blank=True, help_text='Partner logo', null=True, upload_to='partners/')),
                ('website_url', models.URLField(blank=True, help_text='Partner website URL')),
                ('order', models.IntegerField(default=0, help_text='Display order')),
                ('is_active', models.BooleanField(default=True, help_text='Whether this partner is active')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Partner',
                'verbose_name_plural': 'Partners',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='WhatSetsUsApart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Feature title', max_length=200)),
                ('description', models.TextField(help_text='Description of the feature')),
                ('icon', models.CharField(blank=True, help_text='Icon name or identifier (optional)', max_length=100)),
                ('order', models.IntegerField(default=0, help_text='Display order')),
                ('is_active', models.BooleanField(default=True, help_text='Whether this item is active')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'What Sets Us Apart',
                'verbose_name_plural': 'What Sets Us Apart',
                'ordering': ['order', 'created_at'],
            },
        ),
        migrations.CreateModel(
            name='WhoWeAre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='Who We Are', max_length=200)),
                ('content', ckeditor.fields.RichTextField(help_text='Content for the Who We Are section')),
                ('image', models.ImageField(blank=True, help_text='Optional image for the section', null=True, upload_to='about/')),
                ('is_active', models.BooleanField(default=True, help_text='Whether this section is active')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Who We Are',
                'verbose_name_plural': 'Who We Are',
                'ordering': ['-updated_at'],
            },
        ),
    ]
