# Generated by Django

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0003_add_initial_about_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='whoweare',
            name='youtube_video_url',
            field=models.URLField(
                blank=True,
                help_text='Optional YouTube video URL. If set, the video is shown instead of the image on the About page.',
                null=True
            ),
        ),
        migrations.AddField(
            model_name='ourstory',
            name='youtube_video_url',
            field=models.URLField(
                blank=True,
                help_text='Optional YouTube video URL. If set, the video is shown instead of the image on the About page.',
                null=True
            ),
        ),
    ]
