# Generated by Django 6.0 on 2026-02-11 06:54

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0004_publication'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publication',
            name='url',
            field=models.URLField(blank=True, null=True, validators=[django.core.validators.URLValidator()]),
        ),
    ]
